import torch
import torch.nn as nn
from timm.data import resolve_data_config
from timm.data.transforms_factory import create_transform
import timm

# Load the pretrained UNI model
model = timm.create_model("hf-hub:MahmoodLab/uni", pretrained=True, init_values=1e-5, dynamic_img_size=True)
model.eval()

# 1. Show the architecture of the model
print("Model Architecture:")
print(model)

# 2. Show the required transform
transform = create_transform(**resolve_data_config(model.pretrained_cfg, model=model))
print("\nRequired Transform:")
print(transform)


# VisionTransformer(
#   (patch_embed): PatchEmbed(
#     (proj): Conv2d(3, 1024, kernel_size=(16, 16), stride=(16, 16))
#     (norm): Identity()
#   )
#   (pos_drop): Dropout(p=0.0, inplace=False)
#   (patch_drop): Identity()
#   (norm_pre): Identity()
#   (blocks): Sequential(
#     (0): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (1): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (2): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (3): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (4): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (5): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (6): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (7): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (8): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (9): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (10): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (11): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (12): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (13): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (14): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (15): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (16): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (17): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (18): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (19): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (20): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (21): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (22): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#     (23): Block(
#       (norm1): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (attn): Attention(
#         (qkv): Linear(in_features=1024, out_features=3072, bias=True)
#         (q_norm): Identity()
#         (k_norm): Identity()
#         (attn_drop): Dropout(p=0.0, inplace=False)
#         (proj): Linear(in_features=1024, out_features=1024, bias=True)
#         (proj_drop): Dropout(p=0.0, inplace=False)
#       )
#       (ls1): LayerScale()
#       (drop_path1): Identity()
#       (norm2): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#       (mlp): Mlp(
#         (fc1): Linear(in_features=1024, out_features=4096, bias=True)
#         (act): GELU(approximate='none')
#         (drop1): Dropout(p=0.0, inplace=False)
#         (norm): Identity()
#         (fc2): Linear(in_features=4096, out_features=1024, bias=True)
#         (drop2): Dropout(p=0.0, inplace=False)
#       )
#       (ls2): LayerScale()
#       (drop_path2): Identity()
#     )
#   )
#   (norm): LayerNorm((1024,), eps=1e-06, elementwise_affine=True)
#   (fc_norm): Identity()
#   (head_drop): Dropout(p=0.0, inplace=False)
#   (head): Identity()
# )

