_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 63
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.3
            "6": 4.44.1
            "8":
                - 5
            "12": 0.18.3
            "13": linux-x86_64
